services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  TYPO3\CMS\VisualEditor\:
    resource: '../Classes/*'

  TYPO3\CMS\Backend\Template\Components\Buttons\LanguageSelectorBuilder:
    public: true
